//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF.Model
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class UserAccount
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống tên đăng nhập")]
        [Display(Name = "Tên đăng nhập")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống mật khẩu")]
        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }

        [Display(Name = "Trạng thái tài khoản")]
        public Nullable<bool> Status { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống loại")]
        [Display(Name = "Loại tài khoản")]
        public Nullable<byte> UserType { get; set; }
    }
}
